Add global testcontainers header to docs
testcontainers/testcontainers-go pull request #1308
Opened 2023-06-30 13:49 UTC by leocross

## What does this PR do?
Adds a global navigation to the documentation that mirrors the navigation on https://testcontainers.com

## Why is it important?
Testcontainers is a cross-language project and many resources like the getting started article, guides and the modules library that are not specific to a language implementation are hosted one testcontainers.com. Adding a global header with consistent navigation between the project site and the language documentation will help new and existing users discover these resources.

2023-06-30 16:59 UTC, eddumelendez approved these changes
Looks so cool!

2023-07-03 08:45 UTC, cristianrgreco approved these changes

2023-08-04 04:04 UTC, mdelapenya commented on docs/css/extra.css
> -.tc-version {
This is class is needed, as all module pages include an HTML span element using it. Please see https://github.com/testcontainers/testcontainers-go/blob/main/docs/modules/k3s.md?plain=1#L3 as an example.

2023-08-04 04:05 UTC, mdelapenya commented on docs/css/extra.css
> +transition: opacity 0.2s ease;
I think the indentation was removed accidentally here

2023-08-04 04:07 UTC, mdelapenya commented on docs/theme/partials/tc-header.html
> +    "menuItmes": [
```suggestion
    "menuItems": [
```

2023-08-04 04:07 UTC, mdelapenya commented on docs/theme/partials/tc-header.html
> +            {% for menuItem in header["menuItmes"] %}
```suggestion
            {% for menuItem in header["menuItems"] %}
```

2023-08-04 04:08 UTC, mdelapenya requested changes
LGTM although I saw a CSS class being removed but still used across all the module pages. I think once that's restored, we can merge.

Thanks!

2023-08-08 15:03 UTC, mdelapenya submitted a review, later dismissed
LGTM! Thanks!!

@leocross let's talk about improving the CSS for the tc-version block 🙏

2023-08-09 10:34 UTC, mdelapenya approved these changes

2023-08-09 10:35 UTC, merged