feat: add meilisearch-module
testcontainers/testcontainers-go pull request #2835
Opened 2024-10-18 12:15 UTC by mdelapenya

- **feat: add meilisearch**
- **fix**
- **fix**
- **fix**
- **fix**
- **fix**
- **fix**
- **resolve comments**
- **chore: add module scaffolding**
- **resolve comments**
- **resolve comments**
- **add test**
- **docs: fix order**
- **chore: clear errors**

## What does this PR do?
It adds the meilisearch module.

It takes all the commits in #2823, adding the commits needed to add the module to the docs system and the CI.

## Related issues

- Supersedes and Closes #2823
- Closes https://github.com/mashail/testcontainers-go/pull/3

2024-10-18 13:50 UTC, mdelapenya commented on modules/meilisearch/meilisearch.go
> +				ContainerFilePath: "/dumps/" + settings.DumpDataFileName,
@mashail do you think we need to validate the dump files have the `.dump` extension? At least, I think we should include the format in the docs, pointing to the official docs. Wdyt?

2024-10-18 15:00 UTC, mdelapenya commented on modules/meilisearch/meilisearch.go
> +				ContainerFilePath: "/dumps/" + settings.DumpDataFileName,
I went ahead and added it to the docs. In the end, the users using dumps should know the proper format.

Thanks!

2024-10-18 15:16 UTC, stevenh requested changes
Not sure you wanted the description you have currently.

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch.go
> +			return status == 200
suggestion: use the http constant.
```suggestion
			return status == http.StatusOK
```

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch.go
> +	MasterKey string
suggestion: use an internal variable and add a method to access, to avoid people thinking assignment of it is valid.

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +	t.Run("Connect to Address", func(t *testing.T) {
suggestion: remove the run as there is only a single test.

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		client := &http.Client{}
suggestion: just use the default client.

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		req, err := http.NewRequest("GET", address, nil)
suggestion: use the http constant for GET

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		defer resp.Body.Close()
suggestion: just close as the response body is not used below.

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		req, err = http.NewRequest("GET", path, nil)
suggestion: use http constant

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		gresp, err := client.Do(req)
suggestion: reuse `resp` and `err`

2024-10-18 15:16 UTC, stevenh commented on modules/meilisearch/examples_test.go
> +	fmt.Printf("%s \n", meiliContainer.MasterKey)
suggestion: remove trailing space
```suggestion
	fmt.Printf("%s\n", meiliContainer.MasterKey)
```

2024-10-18 15:47 UTC, mdelapenya commented
@stevenh I addressed all your comments 🤞

2024-10-20 14:03 UTC, mashail commented
@mdelapenya thank you for the help and the support.

LGTM @mdelapenya @stevenh

2024-10-21 10:23 UTC, stevenh requested changes
Few nits, but looks like change to remove the unnecessary `t.Run` from the last review was missed?

2024-10-21 10:23 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +	defer resp.Body.Close()
nit: no need for `defer`

2024-10-21 10:23 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +	resp, err := client.Do(req)
nit: no need for a specific variable here
```suggestion
	req, err := http.NewRequest(http.MethodGet, address, nil)
	require.NoError(t, err)

	resp, err := http.DefaultClient.Do(req)
```

2024-10-21 10:23 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +	t.Run("Connect to Address", func(t *testing.T) {
Looks like this was missed?

2024-10-21 10:23 UTC, stevenh commented on modules/meilisearch/meilisearch_test.go
> +		meilisearch.WithMasterKey("my-master-key"))
nit: I find closing the brace on a new line when using multi line syntax like helps be understand the block better.
```suggestion
	ctr, err := meilisearch.Run(ctx, "getmeili/meilisearch:v1.10.3",
		meilisearch.WithDumpImport("testdata/movies.dump"),
		meilisearch.WithMasterKey("my-master-key"),
	)
```

2024-10-21 10:56 UTC, mdelapenya commented
@stevenh everything was addressed. I missed the second `t.Run`, which was removed in [51a4c82](https://github.com/testcontainers/testcontainers-go/pull/2835/commits/51a4c82bf0d386932c7e136e3d7aceefc464e352)

2024-10-21 11:42 UTC, stevenh approved these changes

2024-10-21 11:44 UTC, merged